module.exports = {
    'com': 'search.yahoo.com',
    'uk': 'uk.search.yahoo.com',
    'de': 'de.search.yahoo.com',
    'fr': 'fr.search.yahoo.com',
    'es': 'espanol.search.yahoo.com',
    'nl': 'be.search.yahoo.com',
    'be': 'fr.search.yahoo.com',
    'br': 'br.search.yahoo.com',
    'ca': 'ca.search.yahoo.com',
    'in': 'in.search.yahoo.com',
    'id': 'id.search.yahoo.com',
    'it': 'it.search.yahoo.com',
    'my': 'malaysia.search.yahoo.com',
    'ph': 'ph.search.yahoo.com',
    'qc': 'qc.search.yahoo.com',
    'ro': 'ro.search.yahoo.com',
    'sg': 'sg.search.yahoo.com',
    'se': 'se.search.yahoo.com',
    'vn': 'vn.search.yahoo.com',
    'gr': 'gr.search.yahoo.com',
    'hk': 'hk.search.yahoo.com',
    'tw': 'tw.search.yahoo.com',
}